In [1]:
#What is Descriptive Statistics?
#Mean
#Median
#Mode
#Minimum & Maximum
#Range
#Quartiles (Q1, Q2, Q3)
#Percentiles
#Variance
#Standard Deviation
#Skewness
#Kurtosis

In [2]:
import seaborn as sns

df = sns.load_dataset("titanic")

In [3]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [5]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [6]:
# mean-

df['age'].mean()

np.float64(29.69911764705882)

In [7]:
#median--

df['age'].median()

28.0

In [8]:
# mode

df['embarked'].mode()

0    S
Name: embarked, dtype: object

In [9]:
# first mode--

df['embarked'].mode(0)

0    S
Name: embarked, dtype: object

In [10]:
# min value--

df['age'].min()

0.42

In [11]:
# max value--

df['age'].max()

80.0

In [12]:
# Range = Maximum − Minimum

df['age'].max() - df['age'].min()

79.58

In [13]:
# count

df['age'].count()

np.int64(714)

In [15]:
# sum--

df['fare'].sum()

np.float64(28693.9493)

In [16]:
# variance

df['age'].var()

211.0191247463081

In [17]:
# standard deviation  

df['age'].std()

14.526497332334044

In [18]:

# quartiles

df['age'].quantile(0.25)

np.float64(20.125)

In [19]:
df['age'].quantile(0.75)

np.float64(38.0)

In [20]:
# percentile

df['age'].quantile(0.90)

np.float64(50.0)

In [21]:
df['age'].quantile(0.95)

np.float64(56.0)

In [22]:
# skewness

df['age'].skew()

np.float64(0.38910778230082704)

In [23]:
# kurtosis

df['age'].kurt()

np.float64(0.17827415364210353)

In [24]:
# aggregate multiple statostics

df['age'].agg(['count', 'mean', 'median', 'min', 'max', 'std'])

count     714.000000
mean       29.699118
median     28.000000
min         0.420000
max        80.000000
std        14.526497
Name: age, dtype: float64

In [25]:
# describe all columns

df.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN