In [1]:
import seaborn as sns

df = sns.load_dataset("titanic")

In [2]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [7]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [8]:
# mean--

df['age'].mean()

np.float64(29.69911764705882)

In [9]:
#median--

df['age'].median()

28.0

In [10]:
# mode

df['embarked'].mode()

0    S
Name: embarked, dtype: object

In [11]:
# min value--

df['age'].min()

0.42

In [12]:
# max

df['age'].max()

80.0

In [13]:
# std

df['fare'].std()

49.693428597180905

In [14]:
# var
df['age'].var()

211.0191247463081

In [15]:
# percentiles

df['age'].quantile(0.50)

np.float64(28.0)

In [16]:
#quartiles==

df['age'].quantile([0.25,0.50,0.75])

0.25    20.125
0.50    28.000
0.75    38.000
Name: age, dtype: float64

In [19]:
# IQR

Q1 = df["age"].quantile(0.25)

Q1

np.float64(20.125)

In [20]:
Q3=df['age'].quantile(0.75)
Q3

np.float64(38.0)

In [21]:
IQR=Q3-Q1

In [22]:
IQR

np.float64(17.875)

In [23]:
#Skewness==

df['fare'].skew()

np.float64(4.787316519674893)

In [24]:
#kurtosis

df['fare'].kurt()

np.float64(33.39814088089868)