In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\SHUBHAM\Downloads\credit_card_fraud_10k.csv')

In [3]:
df

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66,3,40,0
1,2,541.82,3,Travel,1,0,87,1,64,0
2,3,237.01,17,Grocery,0,0,49,1,61,0
3,4,164.33,4,Grocery,0,1,72,3,34,0
4,5,30.53,15,Food,0,0,79,0,44,0
...,...,...,...,...,...,...,...,...,...,...
9995,9996,350.91,22,Food,0,0,99,4,37,0
9996,9997,410.04,5,Clothing,0,0,70,3,25,0
9997,9998,527.75,21,Electronics,0,0,44,2,45,0
9998,9999,91.20,2,Electronics,0,0,38,0,37,0
9999,10000,44.06,2,Clothing,0,0,38,0,66,0

In [4]:
df.head()

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66,3,40,0
1,2,541.82,3,Travel,1,0,87,1,64,0
2,3,237.01,17,Grocery,0,0,49,1,61,0
3,4,164.33,4,Grocery,0,1,72,3,34,0
4,5,30.53,15,Food,0,0,79,0,44,0

In [7]:
!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\shubham\anaconda3\lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (2.12.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\shubham\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\shubham\anaconda3\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\shubham\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\shubham\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shubham\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\shubham\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\shubham\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\shubham\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\shubham\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\shubham\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\shubham\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\shubham\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\shubham\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\shubham\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shubham\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\shubham\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\shubham\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\shubham\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\shubham\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\shubham\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shubham\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shubham\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shubham\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shubham\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.11.12)
Requirement already satisfied: patsy>=0.5.6 in c:\users\shubham\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\shubham\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\shubham\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\shubham\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in c:\users\shubham\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\shubham\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [9]:
from ydata_profiling import ProfileReport

# Create profile report
prof = ProfileReport(df, title="EDA Report", explorative=True)

# Save as HTML
prof.to_file(output_file="report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                           | 0/10 [00:00<?, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 39.23it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]